# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cronjob-namespace
---
# Create CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-app
  namespace: cronjob-namespace
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure