# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: job-namespace
---
# Create Job
apiVersion: batch/v1
kind: Job
metadata:
  name: perl-app-job
  namespace: job-namespace
spec:
  template:
    spec:
      containers:
        - name: app
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4