# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: standalone-pod-namespace
---
# Create Standalone Pod
apiVersion: v1
kind: Pod
metadata:
  name: standalone-pod-app
  namespace: standalone-pod-namespace
  labels:
    name: my-app
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
        requests:
          memory: "50Mi"
          cpu: "50m"